#### Data Quality checks

#### Data Quality Checklist


###### Basic dataset overview
###### Missing values summary
###### Duplicates
###### Data type Validation
###### Constant and quasi constant columns
###### ID like columns
###### String inconsistencies
###### High null columns
###### High zero columns (for numeric features)

In [2]:
import pandas as pd
import numpy as np


pd.set_option('display.max_columns', 50)

## load the dataset

In [3]:
df = pd.read_csv("titanic_dataset.csv")

In [4]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
df.shape

(891, 15)

#### Adding few columns for demonstrating data issues

In [6]:
df["passenger_id"] = np.arange(1, len(df) + 1) ####arange is used to create a range of numbers from 1 to the length of the dataframe + 1. This will create a unique passenger_id for each row in the dataframe.

## create a constant column
df["constant_column"] = 1

In [7]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,passenger_id,constant_column
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,1
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2,1
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,3,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,4,1
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,5,1

In [8]:
## create a dirty version of embarked_town
df["embark_town_dirty"] = df["embark_town"].copy()

## select a few random rows (non-missing)
sample_idx = df["embark_town_dirty"].dropna().sample(n=6, random_state=42).index

In [9]:
sample_idx

Index([281, 435, 39, 418, 585, 804], dtype='int64')

In [10]:
df.loc[sample_idx[0:2], "embark_town_dirty"] = df.loc[sample_idx, "embark_town_dirty"].str.upper()
df.loc[sample_idx[2:4], "embark_town_dirty"] = df.loc[sample_idx, "embark_town_dirty"].str.strip().apply(lambda x: f" {x}")
df.loc[sample_idx[4:6], "embark_town_dirty"] = "unknown"

In [11]:
df.iloc[281]

survived                       0
pclass                         3
sex                         male
age                         28.0
sibsp                          0
parch                          0
fare                      7.8542
embarked                       S
class                      Third
who                          man
adult_male                  True
deck                         NaN
embark_town          Southampton
alive                         no
alone                       True
passenger_id                 282
constant_column                1
embark_town_dirty    SOUTHAMPTON
Name: 281, dtype: object

1.1 Basic dataset overview

In [12]:
df.shape

(891, 18)

In [13]:
df.dtypes

survived               int64
pclass                 int64
sex                      str
age                  float64
sibsp                  int64
parch                  int64
fare                 float64
embarked                 str
class                    str
who                      str
adult_male              bool
deck                     str
embark_town              str
alive                    str
alone                   bool
passenger_id           int64
constant_column        int64
embark_town_dirty        str
dtype: object

In [14]:
df.nunique()

survived               2
pclass                 3
sex                    2
age                   88
sibsp                  7
parch                  7
fare                 248
embarked               3
class                  3
who                    3
adult_male             2
deck                   7
embark_town            3
alive                  2
alone                  2
passenger_id         891
constant_column        1
embark_town_dirty      7
dtype: int64

In [15]:
df.describe()

,survived,pclass,age,sibsp,parch,fare,passenger_id,constant_column
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000,891.0
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,446.000000,1.0
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429,257.353842,0.0
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,1.000000,1.0
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400,223.500000,1.0
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,446.000000,1.0
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000,668.500000,1.0
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,891.000000,1.0

#### 1.2 Missing values summary

In [16]:
missing_count = df.isna().sum().sort_values(ascending=False)
missing_percent  = (df.isna().sum() * 100).sort_values(ascending=False)

missing_summary = pd.DataFrame({"missing_count": missing_count, "missing_percent": missing_percent})

print("Missing Values Summary")
missing_summary

Missing Values Summary

                   missing_count  missing_percent
deck                         688            68800
age                          177            17700
embark_town_dirty              2              200
embarked                       2              200
embark_town                    2              200
adult_male                     0                0
constant_column                0                0
passenger_id                   0                0
alone                          0                0
alive                          0                0
survived                       0                0
pclass                         0                0
class                          0                0
fare                           0                0
parch                          0                0
sibsp                          0                0
sex                            0                0
who                            0                0

#### 1.3 Duplicates

In [17]:
duplicates_mask = df.duplicated()
duplicate_sum = duplicates_mask.sum()
print(f"Number of duplicate rows: {duplicate_sum}")


## if to remove duplicates
## df_no_duplicates = df.drop_duplicates()

Number of duplicate rows: 0

###### exampke of fixing a data type if need be

###### df["pclass"] = df["pclass"].astype("int64")  
###### convert pclass to category

### 1.4 Constant and Qualsi-Constant columns

In [18]:
nrows = len(df)
nunique = df.nunique()

constant_cols = nunique[nunique == 1].index.tolist()

print("Constant columns:", constant_cols)

# quasi constant column
quasi_constant_cols = []

for col in df.columns:
    top_freq = df[col].value_counts(normalize=True, dropna=False).values[0]
    if top_freq >= 0.95 and col not in constant_cols:
        quasi_constant_cols.append(col)

print("Quasi-constant columns (top value more than 95%):", quasi_constant_cols)

Constant columns: ['constant_column']
Quasi-constant columns (top value more than 95%): []

In [19]:
df["constant_column"]

0      1
1      1
2      1
3      1
4      1
      ..
886    1
887    1
888    1
889    1
890    1
Name: constant_column, Length: 891, dtype: int64

##### 1.4 ID like columns
##### Columns where number of unique values is closer to number of df rows

In [20]:
n_rows = len(df)
id_like_cols = []

for col in df.columns:
    if df[col].nunique() / n_rows > 0.9:  # Adjust the threshold as needed
        id_like_cols.append(col)
print("ID-like columns (more than 90% unique values):", id_like_cols)

ID-like columns (more than 90% unique values): ['passenger_id']

#### 1.7 String inconsistencies

In [24]:
object_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()
print( object_cols)

['sex', 'embarked', 'class', 'who', 'deck', 'embark_town', 'alive', 'embark_town_dirty']

/var/folders/85/_7ym_kd52wl9lwnxjnhk2mxc0000gn/T/ipykernel_1196/2471503419.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = df.select_dtypes(include=["object", "category"]).columns.tolist()

In [26]:
df["embark_town_clean"] = df["embark_town_dirty"].astype(str).str.strip().str.lower().replace({"unknown": np.nan})

In [27]:
df["embark_town_clean"]

0      southampton
1        cherbourg
2      southampton
3      southampton
4      southampton
          ...
886    southampton
887    southampton
888    southampton
889      cherbourg
890     queenstown
Name: embark_town_clean, Length: 891, dtype: str

In [29]:
high_null_threshold = 0.4
high_null_cols = missing_summary[missing_summary["missing_percent"] >= high_null_threshold * 100]
print("Columns with more than 40% missing values:", high_null_cols)

Columns with more than 40% missing values:                    missing_count  missing_percent
deck                         688            68800
age                          177            17700
embark_town_dirty              2              200
embarked                       2              200
embark_town                    2              200

### 1.9 High zero columns (numeric)