In [20]:
##python -m venv .venv  to create virtual environment

In [21]:
## 3 types of data in ML
### 1. Structured data
### 2. Unstructured data
### 3. Semi-Structured data

In [22]:
## where to get dataset
### kaggle, google dataset search, ucl ml repository, can use ai tools to find dataset
### openpyxl and pyarrow are used to load excel and parquet files

In [23]:
%pip install -q pandas openpyxl pyarrow

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [24]:
import os
import pandas as pd

In [25]:
df_csv = pd.read_csv('titanic.csv')
df_csv.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
df_csv_subject = pd.read_csv(
    filepath_or_buffer= "titanic.csv",
    usecols= [ "Survived", "Pclass",  "Age"]
)
df_csv_subject.head()

   Survived  Pclass   Age
0         0       3  22.0
1         1       1  38.0
2         1       3  26.0
3         1       1  35.0
4         0       3  35.0

In [27]:
df_csv.shape

(891, 12)

In [28]:
#load first N row
df_csv_preview = pd.read_csv("titanic.csv", nrows=5)

In [29]:
df_csv_preview.shape

(5, 12)

In [30]:
## load excel files
df_excel = pd.read_excel("titanic.xlsx")
df_excel.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [31]:
df_excel_subset = pd.read_excel(
    io= "titanic.xlsx",
    usecols= [ "Survived", "Pclass",  "Age"]
)
df_excel_subset.head()

   Survived  Pclass   Age
0         0       3  22.0
1         1       1  38.0
2         1       3  26.0
3         1       1  35.0
4         0       3  35.0

In [32]:
# check sheet names
xls = pd.ExcelFile("titanic.xlsx")
print(xls.sheet_names)

['Sheet1']

In [33]:
# To read a specific sheet, you can use the sheet_name parameter in the read_excel function. For example, to read the first sheet, you can do:
df_first_sheet = pd.read_excel("titanic.xlsx", sheet_name="Sheet1")

In [34]:
# Load parquet files.   parquet is a columnar storage file format that is optimized for use with big data processing frameworks like Apache Spark and Hadoop. It is designed to be efficient in terms of both storage and query performance, making it a popular choice for storing large datasets.
df_parquet = pd.read_parquet("titanic.parquet")
df_parquet.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [35]:
## Load the csv file with different separators.  The default separator is a comma, but you can specify a different separator using the sep parameter. For example, to load a CSV file with a tab separator, you can do:
df_csv_tab = pd.read_csv("titanic_tab.csv", sep="\t") # if it separated by column we use sep = ";"
df_csv_tab.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [36]:
# compare file sizes
csv_file_size = os.path.getsize("titanic.csv")
excel_file_size = os.path.getsize("titanic.xlsx")
parquet_file_size = os.path.getsize("titanic.parquet")

In [37]:
csv_file_size, excel_file_size, parquet_file_size

(60302, 68829, 41399)

In [38]:
def file_size(file_path):
    size_bytes = os.path.getsize(file_path)
    size_kb = size_bytes / 1024
    size_mb = size_kb / 1024
    return size_bytes, size_kb, size_mb

for f in ["titanic.csv", "titanic.xlsx", "titanic.parquet"]:
    size_bytes, size_kb, size_mb = file_size(f)
    print(f"{f}: {size_bytes} bytes, {size_kb:.2f} KB, {size_mb:.2f} MB")

titanic.csv: 60302 bytes, 58.89 KB, 0.06 MB
titanic.xlsx: 68829 bytes, 67.22 KB, 0.07 MB
titanic.parquet: 41399 bytes, 40.43 KB, 0.04 MB

### loading data from a database

In [40]:
%pip install SQLAlchemy psycopg2-binary

Collecting SQLAlchemy
  Downloading sqlalchemy-2.0.51-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.5 kB)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-macosx_11_0_arm64.whl.metadata (4.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in /Users/lezzycan/develop/Data Science/Machine learning/.venv/lib/python3.13/site-packages (from SQLAlchemy) (4.16.0)
Downloading sqlalchemy-2.0.51-cp313-cp313-macosx_11_0_arm64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 12.0 MB/s  0:00:00
Downloading psycopg2_binary-2.9.12-cp313-cp313-macosx_11_0_arm64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 10.7 MB/s  0:00:00 eta 0:00:01
Installing collected packages: SQLAlchemy, psycopg2-binary
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [psycopg2-binary]
Successfully installed SQLAlchemy-2.0.51 psycopg2-binary-2.9.12

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [41]:
import pandas as pd
from sqlalchemy import create_engine

In [45]:
## connect to postgresql database

connection_string = "postgresql://postgres:password@localhost:5432/ml_db"
engine = create_engine(connection_string)

In [ ]:
# load data from csv file to postgresql db table
query =  "SELECT * FROM datasets.diabetes"

df = pd.read_sql(query, con = engine)

In [47]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1